services:
  mysql-ventas:
    image: mysql:8.0
    container_name: mysql-ventas
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_ventas_data:/var/lib/mysql
    networks:
      - ventas-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  back-ventas:
    build: ./Springboot-API-REST
    container_name: back-ventas
    ports:
      - "8080:8080"
    environment:
      DB_ENDPOINT: mysql-ventas
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      mysql-ventas:
        condition: service_healthy
    networks:
      - ventas-net

volumes:
  mysql_ventas_data:

networks:
  ventas-net:
    driver: bridge